### ISSUE TITLE
error in x[[sprintf("flowcore_$p%srmax", k)]] : subscript out of bounds

### ISSUE THREAD

**Issue by Sis021be** [i-cyto/cytofkit#3]
I was trying to read multiple files using flowCore to create ncdfFlowset but received the above error. What do you think I should do?

```
files_B01 <- files[grep("B01", files)];files_B01
-setB01  <- read.ncdfFlowSet(files = files_B01, flowSetId = flowCore:::guid(),isWriteSlice = TRUE) # [1]
```

`error in x[[sprintf("flowcore_$p%srmax", k)]] : subscript out of bounds`

**Comment by SamGG** [comment]
Hi,
This error does not relate to the current package.
Best.
